namespace RandomQuestionGenerator;

public class QuestionStorage
{
    public string[] WebQuestions { get; set; } = new[]
    {
        "Q1: Explain what is the difference between cookies and local storage?",
        "Q2: What is the use of a selector in CSS?",
        "Q3:What is the use of media queries in CSS3?",
        "Q4:What is z-index in CSS?",
        "Q5:What is the difference between UI and UX?",
        "Q6: What is the difference between const, let and var in JavaScript?",
        "Q7: What is a Cookie?",
        "Q8: What is the difference between HTTP and HTTPS?",
        "Q9: What are SSL (Secure Sockets Layer) and TLS (Transport Layer Security)?",
        "Q10: What HTTP verbs do you know?",
        "Q11: How can you reduce page loading time?",
        "Q12: What is CORS? Why is it important?",
        "Q13: What's the difference between classes and IDs in CSS?",
        "Q14: What is a pop-up and what is it used for?",
        "Q15: What is the difference between '==' and '==='?",
        "Q16: Explain the components of the CSS box model.",
        "Q17: What is REST?",
        "Q18: What are the CRUD operations?",
        "Q19: How to include a JavaScript code in a webpage?",
        "Q20: What is the DOM?",
        "Q21: What is JSON and how do we use it?",
        "Q22: What kind of HTTP status codes do you know?"
    };

    public string[] CSharpDotNetQuestions { get; set; } = new[]
    {
        "Q1: What are the access modifiers in C#?",
        "Q2: What is serialization and when is it used?",
        "Q3: What are the OOP principals? Choose one and explain it.",
        "Q4: String vs StringBuilder. What are they and when to use which?",
        "Q5: What is Razor Syntax?",
        "Q6: What is LINQ? When can you use it?",
        "Q7: What are the differences between abstract and virtual methods?",
        "Q8: Can you have an abstract method in a non-abstract class? What about a virtual method in a non-abstract class?",
        "Q9: When should you use abstract methods and when virtual methods?",
        "Q10: What is the 'finally' block and when should you use it?",
        "Q11: What is the difference between 'throw ex' and 'throw'?",
        "Q12: What is an assembly?",
        "Q13: What is the difference between an EXE and a DLL?",
        "Q14: What is a delegate? What types of delegates do you know?",
        "Q15: What is difference between “is” and “as” operators in C#?",
        "Q16: Can the keyword 'this' be used within a Static method? Why?",
        "Q17: What is NullReferenceException and when is it thrown?",
        "Q18: What is the difference between authentication and authorization?",
        "Q19: What is break and continue statement?",
        "Q20: What is a HashSet?",
        "Q21: What is a HashTable?",
        "Q22: What is the 'params' keyword?",
        "Q23: What is routing in ASP.NET Core? How is it done?",
        "Q24: What is boxing/unboxing?",
        "Q25: What is the purpose of a config file in a web application?",
        "Q26 What is the 'virtual' keyword used for?",
        "Q27: What is 'mocking' in the Unit Testing context?",
        "Q28: What are the differences between const and readonly?",
        "Q29: What type of classes do you know of in C#?",
        "Q30: What is a 'sealed' class?",
        "Q31: What is a constructor in a C# class? What differentiate it from other methods?",
        "Q32: What do 'out' and 'ref' keywords do?",
        "Q33: Explain the S.O.L.I.D. principles.",
        "Q34: What is a class and what is an object?",
        "Q35: What is the benefit of ‘using’ statement in C#?",
        "Q36: What is meant by Unmanaged or Managed Code?",
        "Q37: How to properly store passwords?",
        "Q38: What is encryption and decryption?",
        "Q39: What is the difference between Stack and Queue data structure?",
        "Q40: What is recursion?",
        "Q41: What is an event listener?",
        "Q42: What is a callback function? Tell some examples of its usage.",
        "Q43: What is the difference between synchronous and asynchronous execution?",
        "Q44: What is an interface?",
        "Q45: What are reference types and value types?",
        "Q46: What is method overloading?",
        "Q47: Is it possible for a private virtual method to be overridden?",
        "Q48: What are generics in C# .NET?",
        "Q49: In C#, how do you implement the singleton design pattern?",
        "Q50: What are namespaces in C#?",
        "Q51: What are regular expressions in C#?",
        "Q52: What is the garbage collector?",
        "Q53: Which order should we catch the exceptions? Why?",
        "Q54: Why is it not a good practice to write a lot of static methods?",
        "Q55: What is lazy loading?",
        "Q56: What does the 'yield' operator do?",
        "Q57: What is Entity Framework Core?",
        "Q58: What is the difference between code first and DB first approach?",
        "Q59: What is a migration script?",
        "Q60: Name 3 different attributes used in EF Core, what can they do for you?"
    };

    public string[] SQLQuestions { get; set; } = new[]
    {
        "Q1: What is a primary key?",
        "Q2:What is a unique key?",
        "Q3:What is a foreign key?",
        "Q4:What is a join?",
        "Q5:What are the types of join and explain each?",
        "Q6:What is database normalization?",
        "Q7:What is a relationship and what are they?",
        "Q8:What is a query?",
        "Q9:What is subquery?",
        "Q10:What is a stored procedure?",
        "Q11:What is a constraint?",
        "Q12:How to select unique records from a table?",
        "Q13:What are some common clauses used with SELECT query in SQL?",
        "Q14:What is SQL Injection?",
        "Q15: What does the GROUP BY clause do?",
        "Q16: What is a database index?",
        "Q17: How do you modify the structure of a table?",
        "Q18: What are database transactions? When to use?"
    };

}